# yamllint disable rule:document-start
# https://docs.github.com/actions

name: Deploy

on:
  workflow_call:
    secrets:
      FLY_API_TOKEN:
        required: true
        description: Fly.io API Token

permissions:
  contents: read

jobs:
  fly:
    name: Fly.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Use flyctl
        uses: superfly/flyctl-actions/setup-flyctl@fc53c09e1bc3be6f54706524e3b82c4f462f77be # 1.3

      - name: Deploy
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
