# yamllint disable rule:document-start
# https://docs.github.com/actions

name: Secret Manager

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
        description: Name of the secret to sync
      id:
        required: true
        type: string
        description: ID of the secret to sync
    secrets:
      BITWARDEN_ACCESS_TOKEN:
        required: true
        description: Bitwarden Access Token
      FLY_API_TOKEN:
        required: true
        description: Fly.io API Token

jobs:
  bitwarden:
    name: Bitwarden
    runs-on: ubuntu-latest
    steps:
      - name: Get Secrets
        uses: bitwarden/sm-action@v2.0.0
        with:
          access_token: ${{ secrets.BITWARDEN_ACCESS_TOKEN }}
          secrets: ${{ inputs.id }} > ${{ inputs.name }}

      - name: Use flyctl
        uses: superfly/flyctl-actions/setup-flyctl@fc53c09e1bc3be6f54706524e3b82c4f462f77be # 1.3

      - name: Deploy
        run: flyctl secrets set --stage "${{ inputs.name }}=$${{ inputs.name }}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
