# yamllint disable rule:document-start
# https://docs.github.com/actions

name: Secret Manager

on:
  workflow_call:
    inputs:
      request:
        required: true
        type: string
        description: One or more secret Ids to retrieve and the corresponding environment variable name to set
    secrets:
      BITWARDEN_ACCESS_TOKEN:
        required: true
        description: Bitwarden Access Token

jobs:
  bitwarden:
    name: Bitwarden
    runs-on: ubuntu-latest
    steps:
      - name: Get Secrets
        uses: bitwarden/sm-action@v2.0.0
        with:
          access_token: ${{ secrets.BITWARDEN_ACCESS_TOKEN }}
          secrets: ${{ inputs.request }}
